### ISSUE TITLE
HazardCurveGUI-1.5.2 - java.util.zip.ZipException

### ISSUE THREAD

**Issue by davidtrench** [opensha/opensha#99]
I've been getting the following error when I try to run the UCERF3 Complete Model in the HazardCurveGUI-1.5.2.
> java.util.zip.ZipException: error in opening zip file
The application seems to be hanging up on unzipping the downloaded file listed below. 
> cached_dep0.0_depShallow_rakeAll
When I attempt to unzip the file outside of the application it shows as empty. I’ve also attempted to run the application on different computers and the same error appears.

**Comment by kevinmilner** [comment]
Hi @davidtrench, thanks for bringing this to our attention. I believe that this error is due to a recent server configuration change that redirected http requests to https, and the released applications aren't following that redirect. I have reverted the server-side configuration, so it should work again.

Can you give it a try? You will need to either check the "Ignore Cache" box at the bottom of the ERF parameter list, or delete the already downloaded (empty) cached files(in the `.opensha` subdirectory of your user's home directory.

Sorry for the inconvenience and thanks again!

**Comment by davidtrench** [comment]
@kevinmilner that addressed the issue. Thank you for the quick response!
